
    </body>

    <style type="text/css">
         html {
  position: relative;
  min-height: 100%;
}
body {
  /* Margin bottom by footer height */
  margin-bottom: 60px;
}
.footer {
  position: absolute;
  bottom: 0;
  width: 100%;
  color: #e5e5e5;
  /* Set the fixed height of the footer here */
  height: 60px;
  background-color: #090909;
    </style>
    <div class="footer">
<!--        <div class="navbar navbar-default ">-->
            <div class="container">
                <p class="navbar-text pull-left noPrint">© 2016 - Media Phill.</p>
                <p class="navbar-text pull-right noPrint">This site is a project to the subject <a href="#" target="_blank" >mangament project</a></p>
            </div>
<!--        </div>-->
    </div>
</html>
